version: '3.8'

services:
  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    depends_on:
      - user-service
      - question-service
    container_name: frontend-admin

  frontend-user:
    build:
      context: ./frontend/users/peerprep-react
      dockerfile: Dockerfile
    ports:
      - "2999:2999"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/users/peerprep-react:/app
      - /app/node_modules
    depends_on:
      - user-service
      - question-service
    container_name: frontend-user

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}/${USER_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    container_name: user-service

  question-service:
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI}/${QUESTION_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    container_name: question-service

volumes:
  mongodb_data: 